apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k22r
  namespace: kube-system
  labels:
    k8s-app: k22r
spec:
  selector:
    matchLabels:
      name: k22r
  template:
    metadata:
      labels:
        name: k22r
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: k22r
        image: docker.autonubil.net/opsanio/k22r
        imagePullPolicy: Always
        env:
          - name: K22R_COLLECTOR
            value: ipfix.opsanio-elk-mimosa.exanio.net
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
